---
title: "feature-weighted_elasticNet"
author: "Yutong Lu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fwelnet)
library(tidyverse)
library(Metrics)
library(caret)       # for confusionMatrix (accuracy and F1 score)
library(pROC)        # for roc and auc
library(PRROC)       # for pr.curve
```

# load split-1 data

```{r}
# import data from split-1
split1_X_valid2 <- as.matrix(read.csv('../split-1/processed_data/ablation/bace_X_ensemble_valid2_scaled_chemberta+molformer_rawerror.csv'))
split1_y_valid2 <- as.matrix(read.csv('../split-1/processed_data/ablation/bace_y_ensemble_valid2_chemberta+molformer.csv'))

split1_X_test <- as.matrix(read.csv('../split-1/processed_data/ablation/bace_X_ensemble_test_scaled_chemberta+molformer_rawerror.csv'))
split1_y_test <- as.matrix(read.csv('../split-1/processed_data/ablation/bace_y_ensemble_test_chemberta+molformer.csv'))
```

# two groups

```{r}
set.seed(0)

p <- 1154
groups2 <- list(1:2, 3:1154)

# generate Z matrix
z2 <- matrix(0, nrow = p, ncol = length(groups2))
for (i in 1:length(groups2)) {
    z2[groups2[[i]], i] <- 1
}

cvfit2 <- cv.fwelnet(split1_X_valid2, split1_y_valid2, z2, nfolds = 5, family = "binomial")
plot(cvfit2)

cvfit2$lambda.min # value of lambda that gives minimum cross-validated error
cvfit2$lambda.1se # largest value of lambda such that the CV error is within one standard error of the minimum

split1_preds_test2 <- predict(cvfit2, split1_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split1_preds_test2 >= 0.5)), 
  split1_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split1_y_test), as.vector(split1_preds_test2))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split1_preds_test2, weights.class0 = split1_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

# four groups

```{r}
set.seed(0)

p <- 1154
groups3 <- list(1:2, 3:386, 387:1154)  # which features belong to which group

# generate Z matrix
z3 <- matrix(0, nrow = p, ncol = length(groups3))
for (i in 1:length(groups)) {
    z3[groups3[[i]], i] <- 1
}

cvfit3 <- cv.fwelnet(split1_X_valid2, split1_y_valid2, z3, nfolds = 5, family = "binomial")
plot(cvfit3)

cvfit3$lambda.min # value of lambda that gives minimum cross-validated error
cvfit3$lambda.1se # largest value of lambda such that the CV error is within one standard error of the min

split1_preds_test3 <- predict(cvfit3, split1_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split1_preds_test3 >= 0.5)), 
  split1_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split1_y_test), as.vector(split1_preds_test3))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split1_preds_test3, weights.class0 = split1_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

# load split-2 data

```{r}
# import data from split-2
split2_X_valid2 <- as.matrix(read.csv('../split-2/processed_data/ablation/bace_X_ensemble_valid2_scaled_chemberta+molformer_rawerror.csv'))
split2_y_valid2 <- as.matrix(read.csv('../split-2/processed_data/ablation/bace_y_ensemble_valid2_chemberta+molformer.csv'))

split2_X_test <- as.matrix(read.csv('../split-2/processed_data/ablation/bace_X_ensemble_test_scaled_chemberta+molformer_rawerror.csv'))
split2_y_test <- as.matrix(read.csv('../split-2/processed_data/ablation/bace_y_ensemble_test_chemberta+molformer.csv'))
```

# two groups

```{r}
set.seed(0)

p <- 1154
groups2 <- list(1:2, 3:1154)

# generate Z matrix
z2 <- matrix(0, nrow = p, ncol = length(groups2))
for (i in 1:length(groups2)) {
    z2[groups2[[i]], i] <- 1
}

cvfit2 <- cv.fwelnet(split2_X_valid2, split2_y_valid2, z2, nfolds = 5, family = "binomial")
plot(cvfit2)

cvfit2$lambda.min
cvfit2$lambda.1se

split2_preds_test2 <- predict(cvfit2, split2_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split2_preds_test2 >= 0.5)), 
  split2_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split2_y_test), as.vector(split2_preds_test2))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split2_preds_test2, weights.class0 = split2_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

# four groups

```{r}
set.seed(0)

p <- 1154
groups3 <- list(1:2, 3:386, 387:1154) # which features belong to which group

# generate Z matrix
z3 <- matrix(0, nrow = p, ncol = length(groups3))
for (i in 1:length(groups)) {
    z3[groups3[[i]], i] <- 1
}

cvfit3 <- cv.fwelnet(split2_X_valid2, split2_y_valid2, z3, nfolds = 5, family = "binomial")
plot(cvfit3)

cvfit3$lambda.min
cvfit3$lambda.1se

split2_preds_test3 <- predict(cvfit3, split2_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split2_preds_test3 >= 0.5)), 
  split2_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split2_y_test), as.vector(split2_preds_test3))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split2_preds_test3, weights.class0 = split2_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

# load split-3 data

```{r}
# Load the training set of meta-model
split3_X_valid2 <- as.matrix(read.csv('../split-3/processed_data/ablation/bace_X_ensemble_valid2_scaled_chemberta+molformer_rawerror.csv'))
split3_y_valid2 <- as.matrix(read.csv('../split-3/processed_data/ablation/bace_y_ensemble_valid2_chemberta+molformer.csv'))

split3_X_test <- as.matrix(read.csv('../split-3/processed_data/ablation/bace_X_ensemble_test_scaled_chemberta+molformer_rawerror.csv'))
split3_y_test <- as.matrix(read.csv('../split-3/processed_data/ablation/bace_y_ensemble_test_chemberta+molformer.csv'))
```

# two groups

```{r}
set.seed(0)

p <- 1154
groups2 <- list(1:2, 3:1154)

# generate Z matrix
z2 <- matrix(0, nrow = p, ncol = length(groups2))
for (i in 1:length(groups2)) {
    z2[groups2[[i]], i] <- 1
}

cvfit2 <- cv.fwelnet(split3_X_valid2, split3_y_valid2, z2, nfolds = 5, family = "binomial")
plot(cvfit2)

cvfit2$lambda.min
cvfit2$lambda.1se

split3_preds_test2 <- predict(cvfit2, split3_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split3_preds_test2 >= 0.5)), 
  split3_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split3_y_test), as.vector(split3_preds_test2))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split3_preds_test2, weights.class0 = split3_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

# four groups

```{r}
set.seed(0)

p <- 1154
groups3 <- list(1:2, 3:386, 387:1154) # which features belong to which group

# generate Z matrix
z3 <- matrix(0, nrow = p, ncol = length(groups3))
for (i in 1:length(groups)) {
    z3[groups3[[i]], i] <- 1
}

cvfit3 <- cv.fwelnet(split3_X_valid2, split3_y_valid2, z3, nfolds = 5, family = "binomial")
plot(cvfit3)

cvfit3$lambda.min
cvfit3$lambda.1se

split3_preds_test3 <- predict(cvfit3, split3_X_test, type = "response")

# Calculate Accuracy and F1 Score
conf_matrix <- confusionMatrix(table(
  as.numeric((split3_preds_test3 >= 0.5)), 
  split3_y_test))

accuracy <- conf_matrix$overall['Accuracy']
f1_score <- conf_matrix$byClass['F1']

# Calculate ROC AUC
roc_obj <- roc(as.vector(split3_y_test), as.vector(split3_preds_test3))
roc_auc <- auc(roc_obj)

# Calculate PR AUC
pr_obj <- pr.curve(scores.class0 = split3_preds_test3, weights.class0 = split3_y_test,
                   curve = TRUE)
pr_auc <- pr_obj$auc.integral

# Print results
print(paste("Accuracy:", accuracy))
print(paste("F1 Score:", f1_score))
print(paste("ROC AUC:", roc_auc))
print(paste("PR AUC:", pr_auc))
```

